server:
  port: 8888

app:
  api-prefix: /api/v1

#logging:
#  level:
#    org.springframework.web: DEBUG
#    org.springframework.security: DEBUG
#    org.springframework.boot.autoconfigure.web: DEBUG

eureka:
  client:
    server-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: api-gateway
  data:
    redis:
      host: localhost
      port: 6379
  cloud:
    gateway:
      routes:
        - id: login-service
          uri: http://localhost:8081   # URL c?a Login Service
          predicates:
            - Path=${app.api-prefix}/auth/**
          filters:
            - StripPrefix=2
        - id: order-service
          uri: http://localhost:8082   # URL c?a Order Service
          predicates:
            - Path=${app.api-prefix}/order/**
          filters:
            - StripPrefix=2
        - id: product-service
          uri: http://localhost:8083   # URL c?a Order Service
          predicates:
            - Path=${app.api-prefix}/product/**
          filters:
            - StripPrefix=2

keycloak:
  credentials:
    secret: dYHr9v9Nf25PrqrVWptbvQ8vBNIzFAIg
  auth-server-url: http://localhost:8080
  realm: test
  resource: test-author
  bearer-only: true
  public-client: false
  ssl-required: none
  cors: true
  policy-enforcer-config:
    enforcement-mode: ENFORCING
env:
  username: admin
  password: admin123